### ISSUE TITLE
Support my issue 

### ISSUE THREAD

**Issue by thienbui** [athoma28/lao-romanization#2]
I'm Vietnamese, 
I know in Vietnamese is a combination of the characters " a,á , à, ạ, ã... y, ý, ý....
Or English is: a, b, c, d, e, f...

Then in Lao language, which list of characters is it?
Please give me that list!
Thank you!

**Comment by athoma28** [comment]
That list is in laoromanization.csv. It's my own system, and I'm not an expert in Lao, so there may be some rare letters I'm not familiar with or something I didn't notice.

**Comment by thienbui** [comment]
thanks <3
